---
## Common to all nodes
#
- name: Stopping services
  service: name=ceph state=stopped
  ignore_errors: True

- name: Clearing services
  command: pkill -9 ceph
  ignore_errors: True

- name: Purge Ceph
  command: ceph-deploy purge {{ ansible_fqdn }}
  ignore_errors: True

- name: Remove OSD data
  #shell: rm -rf /var/lib/ceph/osd/*/*
  shell: rm -rf /var/lib/ceph/osd/*
  ignore_errors: true

- name: Purge remaining data
  command:  ceph-deploy purgedata {{ ansible_fqdn }}
  ignore_errors: True

- name: Unmounting OSD for HPDL380
  command: chdir=/  umount {{ item }}1
  with_items: devices
  ignore_errors: True
  when: server_model_380 == ansible_product_name

- name: Purge partitions for HPDL380
  shell: parted -s {{ item[0] }} rm {{ item[1] }}
  with_nested:
    - devices 
    - ['1', '2']
  ignore_errors: true
  when: server_model_380 == ansible_product_name


- name: Unmounting OSD for HPSL4540
  command: chdir=/  umount {{ item }}1
  with_items: devices_HPSL4540
  ignore_errors: True
  when: server_model_4540 == ansible_product_name

- name: Purge partitions for HPSL4540
  shell: parted -s {{ item[0] }} rm {{ item[1] }}
  with_nested:
    - devices_HPSL4540
    - ['1', '2']
  ignore_errors: true
  when: server_model_4540 == ansible_product_name

- name: Destroying directories required by ceph
  file: dest=/var/log/ceph state=absent
  file: dest=/etc/ceph state=absent
  file: dest=/var/lib/ceph state=absent
  ignore_errors: True

- name: Uninstalling Ceph packages
  yum: name={{ item }} state=absent
  ignore_errors: True
  with_items:
   - librados2
   - libcephfs
   - libcephfs1
   - librbd1
   - ceph-deploy
   - ceph
   - python-ceph
   - ceph-libs
   - ceph-release
   - ceph-common

#ddd- name: Finding and removing ceph files
#  command: find / -name ceph -exec rm -rf {} \;
#  ignore_errors: True
