---
- hosts:  
   - mons
   - osds
  sudo: True
  roles:
  - common 

- hosts:
   - mons 
  sudo: True
  roles:
  - mons 

- hosts: osds
  sudo: True
  roles:
  - osds 

- hosts:
   - mons
  vars:
    dnsmasq_listen_address: 127.0.0.1
  sudo: True
  tags: rgw
  roles:
  - rgw 

