---
- name: Install Dnsmasq
  yum:
    pkg: dnsmasq
    state: present

- name: Set configuration file
  template:
    src: etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: 'dnsmasq --test --conf-file=%s'
  notify: restart dnsmasq

- name: Set resolve.conf file
  template:
    src: resolve.conf.j2
    dest: /etc/resolv.conf

- name: Make sure Dnsmasq is running
  service:
    name: dnsmasq
    state: started
    enabled: yes
